
services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  docs:
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
  web-majalah:
    build:
      context: .
      dockerfile: ./apps/web-majalah/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production