services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: turborepo-dev
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    volumes:
      - .:/app
